### ISSUE TITLE
Does not display private repositories

### ISSUE THREAD

**Issue by artzub** [artzub/GitHubVisualizer#48]

**Comment by beeblebrox** [comment]
Seems like there was a regression; testing out the site today and it does not show any of my private repos. Private Access is ON.

**Comment by artzub** [comment]
Hmmm. I can look private repos.
I just tried:
on github
![on github](https://cloud.githubusercontent.com/assets/134249/11232349/a2df0d44-8de4-11e5-82e3-c03f83a482a2.png)
on ghv
![on ghv](https://cloud.githubusercontent.com/assets/134249/11232384/036dcec0-8de5-11e5-96a9-a80165c873f1.png)


What a brower do you use?
Can send console output?
You should open dev mode into your brower and remove all data from localstorage into resources tab, and reject the access on github for ghv and try again,

**Comment by beeblebrox** [comment]
I tried everything you suggested and I still don't see private repos.

I upgraded Chrome and I am now using google chrome Version 46.0.2490.86 (64-bit)
I removed all data in the resources tab.
I revoked access to hgv and tried again.

Attached is the console output:
[ghv.artzub.com-1448320319803.txt](https://github.com/artzub/GitHubVisualizer/files/42183/ghv.artzub.com-1448320319803.txt)

Here is a bit more information that may help.  I have 13 public repos (4 source, 9 forks). I have 4 private repos:
![image](https://cloud.githubusercontent.com/assets/498565/11353279/1098212c-91ff-11e5-8879-e447e8480956.png)

I selected to show only source repos to cleanup the screenshot, but the private repos are clearly not there:
![image](https://cloud.githubusercontent.com/assets/498565/11353394/f6cc1ac2-91ff-11e5-9648-180d4a32cc8a.png)

**Comment by artzub** [comment]
The very strange message into console. It message says another app that installed into chrome.
Also we can try to use ammy admin in order to I conect to your computer and look it self.

**Comment by beeblebrox** [comment]
I went ahead and opened up Microsoft Edge and tried this. There are no extensions installed at all in that browser (I think this might be the first time I even opened it).

The private repos are still missing. The console shows nearly the same information (see below).  My original console output was on a linux machine. This is from a windows machine at a different physical address, network, and network provider.

There isn't any time in the near future in which we can setup a remote hosting session, maybe after the new year. I'll be more than glad to provide you with any more information.

<pre>
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
ghv.artzub.com
HTML1300: Navigation occurred.
ghv.artzub.com

ghv.artzub.com (17,13)

ghv.artzub.com (755,9)
undefined
ghv.artzub.com (756,9)
CSI/tbsd_: 983.232ms
CSI/_tbnd: 983.374ms
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
ping (1,322)
</pre>

**Comment by artzub** [comment]
ok, I understood, 
ping:1 give url blablabla
It is facebook plugin.

**Comment by artzub** [comment]
Also I understood what not show private url of your profile, because request https://developer.github.com/v3/repos/#list-user-repositories does not give their.
But request https://developer.github.com/v3/repos/#list-your-repositories must show private repos.

I think what in 2 days must fix it.

**Comment by HACKHERS** [comment]
I just tried, bug still remains

**Comment by artzub** [comment]
I now! I still don't have time to fix it!

**Comment by artzub** [comment]
Now you can look only your (you is owner) private repositories or private repositories of organisations if you have access.
Why? Because the api of github doesn't have nesuary methods for getting inforamtion about private repositories other users even if you have access to them.

**Comment by artzub** [comment]
> Why? Because the api of github doesn't have nesuary methods for getting inforamtion about private repositories other users even if you have access to them.

:stuck_out_tongue_winking_eye: Exsuce me! I had misstake! You can look all your private repositories!

**Comment by HACKHERS** [comment]
Still not showing :(

**Comment by artzub** [comment]
Can you show how it works on you? Because I begun to see my private repositories.

**Comment by beeblebrox** [comment]
I confirm that I see my private repos.

**Comment by HACKHERS** [comment]
Here you are: http://prntscr.com/9t6dko , http://prntscr.com/9t6e8u

**Comment by artzub** [comment]
Try to clear localStorage and other caches and run again. Also remove permission for application from your github profile.
