### ISSUE TITLE
Host on GitHub Pages

### ISSUE THREAD

**Issue by phase** [artzub/GitHubVisualizer#62]
This works perfectly fine on [GitHub Pages](https://github.com/phase/ghv). You can see it in action [here](http://jadonfowler.xyz/ghv). Just switch the main branch to `gh-pages` and you're good to go.

**Comment by artzub** [comment]
Yes! And It is perfect!
But it is not surprisingly, because I have been doing a single-page application =)

And thank you that you noticed it =)
