### ISSUE TITLE
Analyzing private and local repositories

### ISSUE THREAD

**Issue by jehy** [artzub/GitHubVisualizer#65]
Hi! That project is pretty cool but I'd like to analyze a private repo from bitbucket. I think, it can be made locally and it should  not be too complex - can you add this in FAQ?

**Comment by artzub** [comment]
Напиши мне в http://t.me/artzub

**Comment by CosminPerRam** [comment]
I would also like to see the statistics about private repositories from GitHub itself.

**Comment by artzub** [comment]
@CosminPerRam Hi! In the right top corner, you can find the trigger in order to allow private access. 
Note. possible your browser blocked additional windows.

**Comment by CosminPerRam** [comment]
@artzub Hello, thanks for the reply, i still have trouble visualizing the private repositories even after getting the private access to be on (and no, my browser did not blocked the additional window).

**Comment by artzub** [comment]
@CosminPerRam could you give me the user and the repo that you try to visualize.
